apiVersion: v1
kind: Namespace
metadata:
    name: resiliency-testing-example
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: manual
provisioner: docker.io/hostpath
---
apiVersion: v1
kind: PersistentVolume
apiVersion: v1
metadata:
  name: local-message-store
spec:
  capacity:
    storage: 500Mi
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  hostPath:
    path: "/host_mnt/c/temp/volumes/message-store"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-store-claim
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: manual
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mq-broker
spec:
  serviceName: mq-broker
  selector:
    matchLabels:
      app: mq-broker
  replicas: 2
  template:
    metadata:
      labels:
        app: mq-broker
    spec:
      containers:
      - name: mq-broker
        image: rmohr/activemq
        ports:
        - containerPort: 61613
        - containerPort: 61616
        - containerPort: 8161
        volumeMounts:
        - name: mq-message-store
          mountPath: /opt/activemq/data
      volumes:
      - name: mq-message-store
        persistentVolumeClaim:
          claimName: message-store-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mq-broker
  name: mq-broker
spec:
  clusterIP: None
  selector:
    app: mq-broker
  ports:
  - protocol: TCP
    port: 8161
    targetPort: 8161
    name: admin
  - protocol: TCP
    port: 61616
    targetPort: 61616
    name: nio
  - protocol: TCP
    port: 61613
    targetPort: 61613
    name: stomp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mq-broker-0
  name: mq-broker-0
spec:
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: mq-broker-0
  ports:
  - protocol: TCP
    port: 8161
    targetPort: 8161
    name: admin
  - protocol: TCP
    port: 61616
    targetPort: 61616
    name: nio
  - protocol: TCP
    port: 61613
    targetPort: 61613
    name: stomp
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mq-broker-1
  name: mq-broker-1
spec:
  clusterIP: None
  selector:
    statefulset.kubernetes.io/pod-name: mq-broker-1
  ports:
  - protocol: TCP
    port: 8161
    targetPort: 8161
    name: admin
  - protocol: TCP
    port: 61616
    targetPort: 61616
    name: nio
  - protocol: TCP
    port: 61613
    targetPort: 61613
    name: stomp
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mq-broker-0-ingress
  namespace: resiliency-testing-example
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 'mq-broker-0.docker.internal'
    http:
      paths:
      - backend:
          serviceName: mq-broker-0
          servicePort: 8161
        path: /
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mq-broker-1-ingress
  namespace: resiliency-testing-example
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: 'mq-broker-1.docker.internal'
    http:
      paths:
      - backend:
          serviceName: mq-broker-1
          servicePort: 8161
        path: /
---
apiVersion: v1
kind: Service
metadata:
  name: mock-identity-svc
spec:
  selector:
    app: mock-identity-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mock-identity-svc-deployment
  labels:
    app: mock-identity-svc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mock-identity-svc
  template:
    metadata:
      labels:
        app: mock-identity-svc
    spec:
      containers:
      - name: wiremock
        image: rodolpheche/wiremock
        ports:
        - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-svc-deployment
  labels:
    app: identity-svc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: identity-svc
  template:
    metadata:
      labels:
        app: identity-svc
    spec:
      containers:
      - name: identity-svc
        image: localhost:5000/identity-svc
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: identity-svc
spec:
  selector:
    app: identity-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: amq-consumer-deployment
  labels:
    app: amq-consumer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amq-consumer
  template:
    metadata:
      labels:
        app: amq-consumer
    spec:
      containers:
      - name: amq-consumer
        image: localhost:5000/amq-consumer
        ports:
        - containerPort: 8080
        env:
        - name: JAVA_OPTS
          value: -Dspring.profiles.active=KUBE
---
apiVersion: v1
kind: Service
metadata:
  name: amq-consumer
spec:
  selector:
    app: amq-consumer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080

