apiVersion: v1
kind: Namespace
metadata:
    name: resiliency-testing-example
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mq-broker
spec:
  serviceName: activemq-broker-cluster
  selector:
    matchLabels:
      app: mq-broker
  replicas: 1
  template:
    metadata:
      labels:
        app: mq-broker
    spec:
      containers:
      - name: mq-broker
        image: rmohr/activemq
