apiVersion: v1
kind: Namespace
metadata:
    name: resiliency-testing-example
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: message-store-claim
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
    name: mq-broker
spec:
  serviceName: activemq-broker-cluster
  selector:
    matchLabels:
      app: mq-broker
  replicas: 2
  template:
    metadata:
      labels:
        app: mq-broker
    spec:
      containers:
      - name: mq-broker
        image: rmohr/activemq
        ports:
        - containerPort: 61616
        volumeMounts:
        - name: mq-message-store
          mountPath: /opt/activemq/data
      volumes:
      - name: mq-message-store
        persistentVolumeClaim:
          claimName: message-store-claim
